# permissions for end users to view nginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginx-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator-nginx
    app.kubernetes.io/part-of: k8s-operator-nginx
    app.kubernetes.io/managed-by: kustomize
  name: nginx-viewer-role
rules:
  - apiGroups:
      - devops.github.com
    resources:
      - nginxes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - devops.github.com
    resources:
      - nginxes/status
    verbs:
      - get
